function build_stepper_control3_model(modelName)
%BUILD_STEPPER_CONTROL3_MODEL Programmatically create a Simulink model.
%   This creates a discrete model framework for a multi-waypoint,
%   asymmetric S-curve stepper command chain.

if nargin < 1
    modelName = 'stepper_control3_auto';
end

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if exist([modelName '.slx'], 'file')
    delete([modelName '.slx']);
end

new_system(modelName);
open_system(modelName);

set_param(modelName, ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.001', ...
    'StopTime', '10');

add_block('simulink/Sources/From Workspace', [modelName '/vel_ref_ts'], ...
    'VariableName', 'vel_ref_ts', ...
    'Position', [40 60 140 90]);
add_block('simulink/Math Operations/Abs', [modelName '/Abs Speed'], ...
    'Position', [180 60 230 90]);
add_block('simulink/Discontinuities/Saturation', [modelName '/Min Speed Limit'], ...
    'UpperLimit', '1e6', ...
    'LowerLimit', '1', ...
    'Position', [270 60 330 90]);
add_block('simulink/Signal Routing/Goto', [modelName '/Goto Step Rate'], ...
    'GotoTag', 'step_rate_cmd', ...
    'Position', [360 60 430 90]);

add_block('simulink/Logic and Bit Operations/Relational Operator', [modelName '/Direction Compare'], ...
    'Operator', '>=', ...
    'Position', [180 130 260 160]);
add_block('simulink/Sources/Constant', [modelName '/Zero Ref'], ...
    'Value', '0', ...
    'Position', [40 130 90 160]);
add_block('simulink/Signal Attributes/Data Type Conversion', [modelName '/Dir Bool'], ...
    'OutDataTypeStr', 'boolean', ...
    'Position', [300 130 380 160]);
add_block('simulink/Signal Routing/Goto', [modelName '/Goto Dir'], ...
    'GotoTag', 'dir_cmd', ...
    'Position', [410 130 480 160]);

add_block('simulink/Sources/From Workspace', [modelName '/pos_ref_ts'], ...
    'VariableName', 'pos_ref_ts', ...
    'Position', [40 210 140 240]);
add_block('simulink/Sinks/Scope', [modelName '/Trajectory Scope'], ...
    'Position', [510 210 640 280]);
set_param([modelName '/Trajectory Scope'], 'NumInputPorts', '2');

add_block('simulink/Ports & Subsystems/Subsystem', [modelName '/Pulse Generator'], ...
    'Position', [520 40 840 180]);
buildPulseGeneratorSubsystem([modelName '/Pulse Generator']);

add_block('simulink/Signal Routing/From', [modelName '/Step Rate From'], ...
    'GotoTag', 'step_rate_cmd', ...
    'Position', [450 60 500 90]);
add_block('simulink/Signal Routing/From', [modelName '/Dir From'], ...
    'GotoTag', 'dir_cmd', ...
    'Position', [450 130 500 160]);

add_block('simulink/Sinks/Display', [modelName '/Pulse Out'], ...
    'Position', [890 60 980 90]);
add_block('simulink/Sinks/Display', [modelName '/Dir Out'], ...
    'Position', [890 130 980 160]);

add_line(modelName, 'vel_ref_ts/1', 'Abs Speed/1', 'autorouting', 'on');
add_line(modelName, 'Abs Speed/1', 'Min Speed Limit/1', 'autorouting', 'on');
add_line(modelName, 'Min Speed Limit/1', 'Goto Step Rate/1', 'autorouting', 'on');
add_line(modelName, 'vel_ref_ts/1', 'Direction Compare/1', 'autorouting', 'on');
add_line(modelName, 'Zero Ref/1', 'Direction Compare/2', 'autorouting', 'on');
add_line(modelName, 'Direction Compare/1', 'Dir Bool/1', 'autorouting', 'on');
add_line(modelName, 'Dir Bool/1', 'Goto Dir/1', 'autorouting', 'on');
add_line(modelName, 'vel_ref_ts/1', 'Trajectory Scope/1', 'autorouting', 'on');
add_line(modelName, 'pos_ref_ts/1', 'Trajectory Scope/2', 'autorouting', 'on');
add_line(modelName, 'Step Rate From/1', 'Pulse Generator/1', 'autorouting', 'on');
add_line(modelName, 'Dir From/1', 'Pulse Generator/2', 'autorouting', 'on');
add_line(modelName, 'Pulse Generator/1', 'Pulse Out/1', 'autorouting', 'on');
add_line(modelName, 'Pulse Generator/2', 'Dir Out/1', 'autorouting', 'on');

save_system(modelName);
open_system(modelName);
end

function buildPulseGeneratorSubsystem(pathStr)
open_system(pathStr);

try
    delete_line(pathStr, 'In1/1', 'Out1/1');
catch
end
try
    delete_block([pathStr '/In1']);
    delete_block([pathStr '/Out1']);
catch
end

add_block('simulink/Sources/In1', [pathStr '/step_rate'], ...
    'Position', [30 50 60 70]);
add_block('simulink/Sources/In1', [pathStr '/dir_in'], ...
    'Position', [30 120 60 140]);
add_block('simulink/User-Defined Functions/MATLAB Function', [pathStr '/rate_to_pulse'], ...
    'Position', [120 40 290 150]);
add_block('simulink/Sinks/Out1', [pathStr '/step_pulse'], ...
    'Position', [340 60 370 80]);
add_block('simulink/Sinks/Out1', [pathStr '/dir_out'], ...
    'Position', [340 120 370 140]);

script = sprintf([ ...
    'function [pulse, dir_out] = rate_to_pulse(step_rate, dir_in)\n' ...
    '%%#codegen\n' ...
    'persistent phase lastPulse\n' ...
    'Ts = 0.001;\n' ...
    'if isempty(phase)\n' ...
    '    phase = 0;\n' ...
    '    lastPulse = false;\n' ...
    'end\n' ...
    'step_rate = max(step_rate, 0);\n' ...
    'phase = phase + step_rate * Ts;\n' ...
    'pulse = false;\n' ...
    'if phase >= 1\n' ...
    '    phase = phase - floor(phase);\n' ...
    '    pulse = true;\n' ...
    'end\n' ...
    'if pulse && lastPulse\n' ...
    '    pulse = false;\n' ...
    'end\n' ...
    'lastPulse = pulse;\n' ...
    'dir_out = logical(dir_in);\n' ...
    'end\n']);
set_param([pathStr '/rate_to_pulse'], 'Script', script);

add_line(pathStr, 'step_rate/1', 'rate_to_pulse/1', 'autorouting', 'on');
add_line(pathStr, 'dir_in/1', 'rate_to_pulse/2', 'autorouting', 'on');
add_line(pathStr, 'rate_to_pulse/1', 'step_pulse/1', 'autorouting', 'on');
add_line(pathStr, 'rate_to_pulse/2', 'dir_out/1', 'autorouting', 'on');
end
